"""initial catalog and knowledge base

Revision ID: 091d3077ff9b
Revises:
Create Date: 2026-09-11 02:46:14.255423

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "091d3077ff9b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate never emits these — they're not part of Base.metadata. The
    # docker-compose init script also creates them, but a migration must not
    # depend on that: CI and any future managed/production Postgres won't run it.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amenities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.Enum("comfort", "kitchen", "outdoor", "safety", name="amenitycategory"),
            nullable=False,
        ),
        sa.Column("is_free", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "cottages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("area_sqm", sa.Integer(), nullable=False),
        sa.Column("max_guests", sa.Integer(), nullable=False),
        sa.Column("base_guests", sa.Integer(), nullable=False),
        sa.Column(
            "view", sa.Enum("mountains", "pool_and_mountains", name="cottageview"), nullable=False
        ),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("base_guests <= max_guests", name="ck_cottages_base_le_max"),
        sa.CheckConstraint("base_guests > 0", name="ck_cottages_base_guests_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "kb_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_path"),
    )
    op.create_table(
        "bedrooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cottage_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("is_living_room", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("double_beds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("single_beds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sofa_beds", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "double_beds + single_beds + sofa_beds > 0", name="ck_bedrooms_has_at_least_one_bed"
        ),
        sa.CheckConstraint(
            "double_beds >= 0 AND single_beds >= 0 AND sofa_beds >= 0",
            name="ck_bedrooms_bed_counts_non_negative",
        ),
        sa.ForeignKeyConstraint(["cottage_id"], ["cottages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cottage_id", "position", name="uq_bedrooms_cottage_position"),
    )
    op.create_table(
        "cottage_amenities",
        sa.Column("cottage_id", sa.Integer(), nullable=False),
        sa.Column("amenity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["amenity_id"], ["amenities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["cottage_id"], ["cottages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("cottage_id", "amenity_id"),
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "ready", "failed", name="ingestionstatus"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("chunk_count >= 0", name="ck_ingestion_jobs_chunk_count_non_negative"),
        sa.ForeignKeyConstraint(["document_id"], ["kb_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_table(
        "kb_chunks",
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.VECTOR(dim=384), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name="ck_kb_chunks_position_non_negative"),
        sa.ForeignKeyConstraint(["document_id"], ["kb_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("document_id", "position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kb_chunks")
    op.drop_table("ingestion_jobs")
    op.drop_table("cottage_amenities")
    op.drop_table("bedrooms")
    op.drop_table("kb_documents")
    op.drop_table("cottages")
    op.drop_table("amenities")
    # ### end Alembic commands ###

    # Autogenerate does NOT drop the native ENUM types that create_table implicitly
    # created — `drop_table` only drops the table. Without this, re-running
    # `upgrade` after a `downgrade` fails with "type already exists". Drop types
    # only after every table that uses them is gone (Postgres refuses otherwise).
    op.execute("DROP TYPE IF EXISTS ingestionstatus")
    op.execute("DROP TYPE IF EXISTS cottageview")
    op.execute("DROP TYPE IF EXISTS amenitycategory")
    # Extensions are intentionally not dropped: cheap to leave, and dropping one
    # that a later migration also relies on would be an easy way to break things.
