"""add bathrooms to cottages

Revision ID: 2897083f8be3
Revises: 091d3077ff9b
Create Date: 2026-09-13 04:37:00.878376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2897083f8be3"
down_revision: str | Sequence[str] | None = "091d3077ff9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cottages", sa.Column("bathrooms", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cottages", "bathrooms")
    # ### end Alembic commands ###
