"""add availability_blocks

Revision ID: b8dd211f62a6
Revises: 2897083f8be3
Create Date: 2026-09-13 04:48:38.685783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8dd211f62a6"
down_revision: str | Sequence[str] | None = "2897083f8be3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cottage_id", sa.Integer(), nullable=False),
        sa.Column("stay", postgresql.DATERANGE(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("own_booking", "booking_com", "manual", name="availabilitysource"),
            nullable=False,
        ),
        sa.Column("external_uid", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("cottage_id"), "="),
            (sa.column("stay"), "&&"),
            using="gist",
            name="ck_availability_blocks_no_overlap",
        ),
        sa.CheckConstraint("NOT isempty(stay)", name="ck_availability_blocks_stay_not_empty"),
        sa.ForeignKeyConstraint(["cottage_id"], ["cottages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_uid", name="uq_availability_blocks_external"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("availability_blocks")
    # ### end Alembic commands ###

    # See the initial migration: drop_table doesn't drop the native ENUM type.
    op.execute("DROP TYPE IF EXISTS availabilitysource")
